### ISSUE TITLE
Access Token in drbCreateClient

### ISSUE THREAD

**Issue by sohamm17** [Dwii/Dropbox-C#5]
In the `drbCreateClient` function, you have key and secret for user where as `DbxClient` for Java Core Dropbox API, they only have access token. Which one should I use key/secret for the access token?

**Comment by sohamm17** [comment]
Okay. Got the point that the key and secret are different from access token I am talking about! Can you please tell me what is reason for the access token in the DropBox App Console?

**Comment by Dwii** [comment]
Hi sohamm17,

Once acquired, the access token (the key/secret pair) can be reused in the future.

The printf at the [line 54 in example.c](https://github.com/Dwii/Dropbox-C/blob/master/Dropbox/example/example.c#L54) only serve the purpose of the example (in a way that keep the example simple): it show you how to get your access token.

For instance, if you get the following output in the console:
<pre>
key:    foo
secret: bar
</pre>
you can write these values in the [line 30 and 31](https://github.com/Dwii/Dropbox-C/blob/master/Dropbox/example/example.c#L30):

```c
    // User key and secret. Leave them NULL or set them with your AccessToken.
    char *t_key    = "foo"; //< access token key
    char *t_secret = "bar";  //< access token secret
```
That way, you won't have to request a new access token on each execution of your program.

Of course, in a __real project__, these values should not be hard coded, but stored in a file or somewhere.

**Comment by sohamm17** [comment]
I realized it. Thank you!
However, I noticed one thing that in the Java Dropbox APIs, they can create a client with an access token (a single value, not key-secret pair values). This access token can be generated from the App Console and can be given at the application program code. Then you are good to go. You don't need to open an URL and authorize the app. I know it's for testing purpose. Is there any similar way your API supports that?

**Comment by Dwii** [comment]
No, the Java API use the OAuth2 protocol while Dropbox-C still use OAuth1, which use a different authorization flow. Unfortunately, I didn't manage to find any C library for OAuth2, nor time to write one.

By the way, I see in the [Java API documentation](https://www.dropbox.com/developers/core/start/java) that the authorization process still requires the user to open a URL and authorize the app in the first step:

```java
// Have the user sign in and authorize your app.
String authorizeUrl = webAuth.start();
System.out.println("1. Go to: " + authorizeUrl);
System.out.println("2. Click \"Allow\" (you might have to log in first)");
System.out.println("3. Copy the authorization code.");
String code = new BufferedReader(new InputStreamReader(System.in)).readLine().trim();
```
(Or I might missed something, I never used the Java library.)

**Comment by sohamm17** [comment]
Okay. Now I got it.
Actually, that's process to open the URL. However, you can directly give the access code as well to create a client with a config.

```
DbxClient client = new DbxClient(config, accessToken);
System.out.println("Linked account: " + client.getAccountInfo().displayName);
```

That's little below the code you shared.

**Comment by Dwii** [comment]
Exactly, as you can do it in Dropbox-C, if you stored the previous access __token__ (t_key and t_secret) somewhere:
```c
drbClient* cli = drbCreateClient(c_key, c_secret, t_key, t_secret);
```

**Comment by sohamm17** [comment]
Yeah! but `accessToken` is a single string which can be generated here: https://www.dropbox.com/developers/apps in specific App's page. You don't need to open an URL any time.

**Comment by Dwii** [comment]
Oh! I ignored that :)

**Comment by sohamm17** [comment]
Ok. Closing this issue as it's not possibly one.
