### ISSUE TITLE
asprintf issue

### ISSUE THREAD

**Issue by Diana-B** [Dwii/Dropbox-C#6]
Hey Dwii,

Having the following issue while trying to use your API on Windows (trying to compile the example):
**.\src\dropbox.c|156|undefined reference to `asprintf'|**

Do you know how to solve this issue?
I'm using Code::Blocks with mingw32 GCC compiler.

Diana

**Comment by Dwii** [comment]
Hey Diana,

I wrote Dropbox-C for Linux and Mac OS X but not Windows, so you might face some issues like this if you try to compile it on this platform (I never tried myself). The function 'asprintf' is a GNU extension in stdio.h (see http://man7.org/linux/man-pages/man3/asprintf.3.html) so it might not be available on Windows.

I just googled 'asprintf windows' and this might solve this problem: http://asprintf.insanecoding.org/

Dwii
